// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjYknXJRwdea7ftHw2BZGeXXGRrYWkAiU',
    appId: '1:879330643441:web:5298606b97920dd8bd4850',
    messagingSenderId: '879330643441',
    projectId: 'bidapparelsc',
    authDomain: 'bidapparelsc.firebaseapp.com',
    storageBucket: 'bidapparelsc.firebasestorage.app',
    measurementId: 'G-JMFRCCC35C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtFwk3bfXGOtmOPRI-sZ2jXDiTzDUklT8',
    appId: '1:879330643441:android:065a13ac8890523fbd4850',
    messagingSenderId: '879330643441',
    projectId: 'bidapparelsc',
    storageBucket: 'bidapparelsc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEPXa6rbFIS6z2juQ-Mz8_wu8TIolqdok',
    appId: '1:879330643441:ios:28fb15a8ef4f95bebd4850',
    messagingSenderId: '879330643441',
    projectId: 'bidapparelsc',
    storageBucket: 'bidapparelsc.firebasestorage.app',
    iosBundleId: 'com.example.bid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEPXa6rbFIS6z2juQ-Mz8_wu8TIolqdok',
    appId: '1:879330643441:ios:28fb15a8ef4f95bebd4850',
    messagingSenderId: '879330643441',
    projectId: 'bidapparelsc',
    storageBucket: 'bidapparelsc.firebasestorage.app',
    iosBundleId: 'com.example.bid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjYknXJRwdea7ftHw2BZGeXXGRrYWkAiU',
    appId: '1:879330643441:web:65a8375c0b7549b1bd4850',
    messagingSenderId: '879330643441',
    projectId: 'bidapparelsc',
    authDomain: 'bidapparelsc.firebaseapp.com',
    storageBucket: 'bidapparelsc.firebasestorage.app',
    measurementId: 'G-LT0J7JFJBP',
  );
}
